const LOADING_STATES = {
    FETCHING: "FETCHING",
    FETCHED_BUT_EMPTY: "FETCHED_BUT_EMPTY",
    FETCHED_AND_AVAILABLE: "FETCHED_AND_AVAILABLE",
    ERROR: "ERROR"
}

Object.freeze(LOADING_STATES);

export default LOADING_STATES;