export const TABLE_FILTERS_ACTION_TYPES = {
    SET_PAGE_NUMBER: "SET_PAGE_NUMBER",
    SET_SHOW_BY_VALUE: "SET_SHOW_BY_VALUE",
    SET_SEARCH_STRING: "SET_SEARCH_STRING",
    SET_SELECTED_FILTERS: "SET_SELECTED_FILTERS",
    RESET_FILTERS: "RESET_FILTERS"
}